name: Cleanup merge branches after PR close

on:
  pull_request:
    types:
      - closed

jobs:
  delete-merge-branch:
    if: startsWith(github.event.pull_request.head.ref, 'merge-master-into-dev-4.0-')
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "Deleting branch: $BRANCH_NAME"
          curl -s -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
